const plants = [
  {
    image: "",
    price: 15.99,
    weight: "2kg",
    oldPrice: 18.99,
    name: "Fern",
    origin: "Brazil",
  },
  {
    image: "",
    price: 20.49,
    weight: "3kg",
    oldPrice: 25.99,
    name: "Cactus",
    origin: "Mexico",
  },
  {
    image: "",
    price: 12.99,
    weight: "1.5kg",
    oldPrice: 14.99,
    name: "Bamboo",
    origin: "China",
  },
  {
    image: "",
    price: 18.99,
    weight: "2.5kg",
    oldPrice: 22.49,
    name: "Aloe Vera",
    origin: "Egypt",
  },
  {
    image: "",
    price: 22.99,
    weight: "3kg",
    oldPrice: 28.99,
    name: "Snake Plant",
    origin: "West Africa",
  },
  {
    image: "",
    price: 10.99,
    weight: "1kg",
    oldPrice: 13.99,
    name: "Peace Lily",
    origin: "Colombia",
  },
  {
    image: "",
    price: 14.99,
    weight: "2kg",
    oldPrice: 17.99,
    name: "Spider Plant",
    origin: "South Africa",
  },
  {
    image: "",
    price: 19.99,
    weight: "2.8kg",
    oldPrice: 24.99,
    name: "Rubber Plant",
    origin: "India",
  },
  {
    image: "",
    price: 25.99,
    weight: "3.5kg",
    oldPrice: 30.99,
    name: "Fiddle Leaf Fig",
    origin: "West Africa",
  },
  {
    image: "",
    price: 15.49,
    weight: "2.2kg",
    oldPrice: 18.49,
    name: "Succulent",
    origin: "Morocco",
  },
  {
    image: "",
    price: 17.99,
    weight: "1.8kg",
    oldPrice: 20.99,
    name: "Lavender",
    origin: "France",
  },
  {
    image: "",
    price: 11.99,
    weight: "1.2kg",
    old,
  },
];
